export {default as Home} from './home/Home'
export {default as SearchResult} from './searchResult/SearchResult'
export {default as Explore} from './explore/Explore'
export {default as Details} from './details/Details'
export {default as NotFound} from './404/NotFound'